### ISSUE TITLE
Can't build test sites

### ISSUE THREAD

**Issue by SergioB** [ufront/mvc-platform-test#2]
I've tried it with haxe testsites.hxml but I'm getting the error:
Routes.hx:4 class not found MultiValueMap, it seems that this class exists on github, but not on haxelib. Because ufront is dependent on a lot of libraries and it is difficult to install everything from github - I see the solution as pushing to haxelib the latest ufront, it seems that MultiVarMap was added on January so it should be tested by now.

**Comment by jasononeil** [comment]
Sorry I didn't see this from so long ago.  This problem is fixed for now, but in general I intend to use these platform tests in conjunction with TravisCI, because the setup is quite difficult to get right.
